### ISSUE TITLE
скруглять уголки

### ISSUE THREAD

**Issue by illus0r** [illus0r/primat#1]
Технически, скруглять уголки можно. https://www.w3.org/TR/SVG/paths.html#PathDataEllipticalArcCommands

**Comment by MainOlma** [comment]
для прорисовки коннекторов у нас используются особые кривые
https://github.com/d3/d3-shape#curveStepBefore
они безо всяких скруглений

я искала, как можно их модифицировать, нашла лишь один ответ на эту тему

я проверила это решение. оно работает неправильно, по крайней мере с текущей версией d3
https://gist.github.com/larsenmtl/8f26a673f66801ab34ef0fa352662627

предлагаю пока отложить эту задачу
