### ISSUE TITLE
Уменьшить отступ между таксонами и правой колонкой как на макете

### ISSUE THREAD

**Issue by illus0r** [illus0r/primat#10]
![image](https://user-images.githubusercontent.com/797993/44511558-a3646f00-a6c0-11e8-9ff1-30010bcb7fa4.png)

Надо уменьшить. В цеплине обновил:
![image](https://user-images.githubusercontent.com/797993/44511631-d3ac0d80-a6c0-11e8-96e5-78db2943f849.png)

**Comment by MainOlma** [comment]
сделаю отступ,  ориентируясь по самому слоистому месту
![image](https://user-images.githubusercontent.com/40692017/44521595-3f4fa400-a6dc-11e8-88e2-26b4520513ea.png)
