### ISSUE TITLE
Если дитё начинается почти сразу после родителя, линк от родителя отъезжает

### ISSUE THREAD

**Issue by illus0r** [illus0r/primat#12]
Кажется, надо букву Г уменьшать в таких случаях. А в остальных наоборот, побольше бы. Как на макете. Если сложно, дай знать.

![image](https://user-images.githubusercontent.com/797993/44573562-a4180680-a78f-11e8-8c4f-aa7641399904.png)

**Comment by MainOlma** [comment]
у тебя там 8 пикселей. сделаю столько
если разница будет меньше этого значения, то связь пойдёт сразу вниз от начала родителя
