### ISSUE TITLE
«Поздний плейстоц»

### ISSUE THREAD

**Issue by illus0r** [illus0r/primat#14]
![image](https://user-images.githubusercontent.com/797993/44574177-53a1a880-a791-11e8-8a8c-a1eb7a529101.png)

**Comment by MainOlma** [comment]
да, бедняга не помещается

**Comment by MainOlma** [comment]
он упирается в конец свг.  что делать с ним? ради него свг увеличить? или его одного насильственно от края отодвигать?

**Comment by illus0r** [comment]
А у тебя же шапка на отдельном СВГ? Можно её чуть увеличить, не двигая правую колонку? @MainOlma

**Comment by MainOlma** [comment]
после комита пришло письмо
Page build failure

и соответственно на сайте не обновилось

**Comment by MainOlma** [comment]
с последним комитом всё правильно обновилось
