### ISSUE TITLE
Кирпичи выпадают

### ISSUE THREAD

**Issue by illus0r** [illus0r/primat#16]
![image](https://user-images.githubusercontent.com/797993/44574467-2acde300-a792-11e8-9bfd-28ecb115ac11.png)

**Comment by MainOlma** [comment]
славно подебажила, а ошибка оказалась в данных - начало и конец периодов существования были перепутаны:
![image](https://user-images.githubusercontent.com/40692017/44596490-09dab180-a7d5-11e8-8904-87381e7311ee.png)
от этого неправильно находилась правая граница
