### ISSUE TITLE
Прятать полоски и бегунок под лейблами, кирпичами и названиями таксонов (только названиями, не под рамочками)

### ISSUE THREAD

**Issue by illus0r** [illus0r/primat#18]
Обновил цеплин. На макете бегунок остался над надписями, но, думаю, идея понятна, спрашивай, если что.
![image](https://user-images.githubusercontent.com/797993/44601113-229e9380-a7e4-11e8-8528-58a58af0d5f0.png)

**Comment by MainOlma** [comment]
Многое надо будет переделать в алгоритме.
Нет простого z-index  как в css
Элементы слоятся в порядке их добавления на сцену.
У меня сейчас сначала рисуются таксоны и тут же на них кирпичи с подписями, а потом коннекторы, то есть они сверху крипичей с подписями.

**Comment by MainOlma** [comment]
я тут подумала это ведь можно сделать после всего построения просто уже в готовом ДОМе поменять две группы местами taxons и connections
![image](https://user-images.githubusercontent.com/40692017/44608465-859c2480-a7fc-11e8-9846-81ff11b5a7ca.png)

**Comment by illus0r** [comment]
@MainOlma 
Супер. Теперь надо:
- [ ]  серые плашки подсемейств поменять на #000000, 7% opacity. Тогда линии будут просвечивать.
- [ ] Полоска «Сейчас» должна быть выше всего остального.
- [x] Хорошо бы отодвинуть немного правую границу текста от «сейчас», пикселей на 5…10. Прилипает.
- [ ] Бегунок должен тоже пропадать под лейблами. Но не под линками.
- [x] Белые полупрозрачные плашки под кирпичами и лейблами
