### ISSUE TITLE
Отступы между лейблами, кирпичами и рамками сделать как на макете

### ISSUE THREAD

**Issue by illus0r** [illus0r/primat#20]

**Comment by MainOlma** [comment]
вот ты говоришь всё как на макете, как на макете, а на макете криво и непонятно

посмотрим расстояния по горизонтали:
от серого квадрата до первого белого 10px
а до следующего белого уже 12px

по вертикали же в обоих случаях по 18 px

Это так и было задумано?

И надо признаться, что такой контент наложением неудобно проверять
Давай уточним все ключевые отступы, типа:
между таксонами, между таксонами и бриками, между таксоном и его названием

**Comment by illus0r** [comment]
Дублирует #32
