### ISSUE TITLE
Тени у рамок — как на макете :–)

### ISSUE THREAD

**Issue by illus0r** [illus0r/primat#21]

**Comment by MainOlma** [comment]
если б это был css  я б копирнула из макета не задумываясь, 
но у нас вот что:
`function initFilter(){
        /* For the drop shadow filter*/
        var defs = svg.append("defs");

        var filter = defs.append("filter")
            .attr("id", "dropshadow")
            .attr("height", "130%");

        filter.append("feGaussianBlur")
            .attr("in", "SourceAlpha")
            .attr("stdDeviation", 4)
            .attr("result", "blur");
        filter.append("feOffset")
            .attr("in", "blur")
            .attr("dx", 2)
            .attr("dy", 2)
            .attr("result", "offsetBlur");

        var feMerge = filter.append("feMerge");

        feMerge.append("feMergeNode")
            .attr("in", "offsetBlur")
        feMerge.append("feMergeNode")
            .attr("in", "SourceGraphic");
    }`
так что параметры выбраны на глаз.
надо поярче?)

**Comment by illus0r** [comment]
```
box-shadow: 0 1px 8px 0 rgba(0, 0, 0, 0.2);
            ↑ ↑   ↑   ↑      ↑
            | |   |   |      цвет и прозрачность
            | |   |   spread, кажется, можно не задавать в СВГ
            | |   stdDeviation?
            | dy
            dx      
```
@MainOlma
