### ISSUE TITLE
Те, кто сейчас жив, должен дотягиваться до линии «сейчас». Вообще шик, если два правых уголка сможем не скруглять

### ISSUE THREAD

**Issue by illus0r** [illus0r/primat#23]
![image](https://user-images.githubusercontent.com/797993/44615432-c4ed6400-a842-11e8-8be6-7f5ed8bd392e.png)

**Comment by MainOlma** [comment]
для этого надо заменить rect на path, что разрушит нам логику работы со связями. так что я их подвину, но пусть будет скруглённым по всем углам. ок?

**Comment by illus0r** [comment]
ok
