### ISSUE TITLE
Решить проблему праймеров

### ISSUE THREAD

**Issue by illus0r** [illus0r/primat#4]
Думаю, что с ними делать. Может нужен «призрак дядюшки», то есть общий родственник, которого мы сами придумаем?

Он будет пунктирный какой-нибудь. Или линия будет раздваиваться как-то

**Comment by MainOlma** [comment]
напомни суть проблемы

**Comment by illus0r** [comment]
@MainOlma 
Некоторые потомки в таймлайне раньше предков. График ломается:
![image](https://user-images.githubusercontent.com/797993/45147273-3fb46880-b1cd-11e8-9d11-482bbac084f0.png)

Предлагаю решить так, на макете есть:
![image](https://user-images.githubusercontent.com/797993/45147302-4e9b1b00-b1cd-11e8-9b31-d35faf196f52.png)
