### ISSUE TITLE
По-другому выводить линки

### ISSUE THREAD

**Issue by illus0r** [illus0r/primat#5]
![image](https://user-images.githubusercontent.com/797993/44510783-45368c80-a6be-11e8-9836-cf16d68ec121.png)

**Comment by MainOlma** [comment]
а в этом случае линки должны остаться такими как есть?
![image](https://user-images.githubusercontent.com/40692017/44532229-4a65fc80-a6fb-11e8-8a77-fae995a3852e.png)

может ты мне изобразишь все кейсы

**Comment by MainOlma** [comment]
ага. этот случай опишем так 
`if (x1To>x1From && x1To<x2From) xSource=x1To-3`

From - кирпич откуда - родитель
To - кирпич куда - потомок
Source - точка начала коннектора

**Comment by MainOlma** [comment]
внимание на 56ой кирпич
![image](https://user-images.githubusercontent.com/40692017/44545956-24eaea00-a71f-11e8-8956-de111fe41b7c.png)
